name: Deploy to AWS EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Env-specific Config
        id: set-config
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "AMI_ID=ami-dev" >> $GITHUB_ENV
            echo "SUBNET_ID=subnet-dev" >> $GITHUB_ENV
            echo "SG_ID=sg-dev" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "stage" ]]; then
            echo "AMI_ID=ami-stage" >> $GITHUB_ENV
            echo "SUBNET_ID=subnet-stage" >> $GITHUB_ENV
            echo "SG_ID=sg-stage" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "AMI_ID=ami-prod" >> $GITHUB_ENV
            echo "SUBNET_ID=subnet-prod" >> $GITHUB_ENV
            echo "SG_ID=sg-prod" >> $GITHUB_ENV
          fi

      - name: Launch EC2 Instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id $AMI_ID \
            --instance-type t2.micro \
            --key-name devops-key \
            --security-group-ids $SG_ID \
            --subnet-id $SUBNET_ID \
            --count 1 \
            --region $AWS_REGION \
            --query "Instances[0].InstanceId" \
            --output text)
          echo "Launched Instance ID: $INSTANCE_ID"
