name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger on push to main branch
  pull_request:
    branches:
      - master  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y git maven

      - name: Build the project
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure build job is completed before deploying
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: 'prod'  # Change as needed
        run: |
          chmod +x launch-ec2.sh
          ./launch-ec2.sh $STAGE
