name: EC2 Deploy Automation

on:
  push:
    branches: [master]  # Use 'main' if that's your branch name
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH to EC2
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Print EC2 identity
            echo "Logged into EC2 instance"

            # Install dependencies
            sudo yum update -y
            sudo yum install -y java-21-amazon-corretto git maven

            # Clone and build the app
            rm -rf ec2-deploy-automation || true
            git clone https://github.com/Erharshita-cloud/ec2-deploy-automation.git
            cd ec2-deploy-automation

            # Run the Java App
            mvn clean package

            # Kill existing app (if any)
            sudo pkill -f 'java -jar' || true

            # Run the JAR file
            nohup java -jar target/*.jar > app.log 2>&1 &

            # Wait a few seconds for the app to start
            sleep 10

            # Test if port 80 is working
            curl -I http://localhost || echo "App not responding on port 80"
            
            # Schedule instance shutdown in 2 minutes
            sudo shutdown -h +2 "Auto-shutdown for cost saving"
          EOF
