name: EC2 Deploy Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH to EC2
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Install dependencies
            sudo yum update -y
            sudo yum install -y java-21-amazon-corretto git maven

            # Clone project repo
            rm -rf techeazy-devops || true
            git clone https://github.com/techeazy-consulting/techeazy-devops.git
            cd techeazy-devops

            # Build the Maven project
            mvn clean package

            # Kill existing app if running
            sudo pkill -f 'java -jar' || true

            # Run app
            nohup java -jar target/*.jar > app.log 2>&1 &
          EOF

